#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config focused_border_color "#5E81AC"
bspc config normal_border_color "#3B4252"
bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

${HOME}/.fehbg
compton &
polybar example