#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config focused_border_color "#4C566A"
bspc config normal_border_color "#434C5E"
bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a steam state=floating
bspc rule -a emulator state=floating
bspc rule -a Lutris state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ${HOME}/Pictures/wallpaper_3.jpg
picom --experimental-backends &
$HOME/.config/polybar/launch.sh