#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

# bspc config focused_border_color "#576e74"
# bspc config normal_border_color "#002b35"
bspc config border_width 0
bspc config border_radius 4
bspc config window_gap 18

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

nitrogen --set-zoom-fill $HOME/.wallpapers/wallpaper_27.png
picom &
$HOME/.config/polybar/launch.sh
spotify-listener &
disown
